# NVIDIA DCGM Exporter configuration
# Exports GPU metrics to Prometheus

serviceMonitor:
  enabled: true

# Force dcgm-exporter to run ONLY on GPU nodes (using NFD label)
nodeSelector:
  feature.node.kubernetes.io/pci-0300_10de.present: "true"

tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
