# Dragonfly CR Template
# Creates Dragonfly instance using operator

apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas | default 1 }}

  image: {{ .Values.image }}

  {{- if .Values.args }}
  args:
    {{- range .Values.args }}
    - {{ . }}
    {{- end }}
  {{- end }}

  {{- if .Values.resources }}
  resources:
    {{- if .Values.resources.requests }}
    requests:
      cpu: {{ .Values.resources.requests.cpu | quote }}
      memory: {{ .Values.resources.requests.memory | quote }}
    {{- end }}
    {{- if .Values.resources.limits }}
    limits:
      cpu: {{ .Values.resources.limits.cpu | quote }}
      memory: {{ .Values.resources.limits.memory | quote }}
    {{- end }}
  {{- end }}

  {{- if .Values.snapshot }}
  snapshot:
    {{- if .Values.snapshot.cron }}
    cron: {{ .Values.snapshot.cron | quote }}
    {{- end }}
    {{- if .Values.snapshot.dir }}
    dir: {{ .Values.snapshot.dir | quote }}
    {{- end }}
    {{- if .Values.snapshot.persistentVolumeClaimSpec }}
    persistentVolumeClaimSpec:
      accessModes:
        {{- range .Values.snapshot.persistentVolumeClaimSpec.accessModes }}
        - {{ . }}
        {{- end }}
      resources:
        requests:
          storage: {{ .Values.snapshot.persistentVolumeClaimSpec.resources.requests.storage }}
      {{- if .Values.snapshot.persistentVolumeClaimSpec.storageClassName }}
      storageClassName: {{ .Values.snapshot.persistentVolumeClaimSpec.storageClassName }}
      {{- end }}
    {{- end }}
  {{- end }}
