apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/munhq/kubernetes_gpu.git
        revision: main
        files:
          - path: "ansible/argocd/projects/*.yaml"
  template:
    metadata:
      name: 'project-{{ .path.basename }}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/munhq/kubernetes_gpu.git
        targetRevision: main
        path: 'ansible/argocd/projects'
        directory:
          include: '{{ .path.filename }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
