apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: batch-api
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: platform
            namespace: default
            project: platform
  template:
    metadata:
      name: 'batch-api'
      namespace: argocd
      labels:
        app: batch-inference-api
        environment: '{{ .env }}'
    spec:
      project: '{{ .project }}'
      source:
        repoURL: https://github.com/munhq/kubernetes_gpu.git
        targetRevision: main
        path: ansible/argocd/charts/batch-inference-api
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
