apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dcgm-exporter
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: infrastructure
            namespace: monitoring
            project: infrastructure
            helmRepo: https://nvidia.github.io/dcgm-exporter/helm-charts
            helmChart: dcgm-exporter
            helmVersion: 3.6.1
  template:
    metadata:
      name: 'dcgm-exporter'
      namespace: argocd
      labels:
        app: dcgm-exporter
        environment: '{{ .env }}'
    spec:
      project: '{{ .project }}'
      sources:
        - repoURL: '{{ .helmRepo }}'
          chart: '{{ .helmChart }}'
          targetRevision: '{{ .helmVersion }}'
          helm:
            releaseName: dcgm-exporter
            valueFiles:
              - $values/ansible/argocd/config/dcgm-exporter/values.yaml
        - repoURL: https://github.com/munhq/kubernetes_gpu.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
