apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kuberay-operator
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: gpu
            namespace: gpu-workloads
            project: gpu
            helmRepo: https://ray-project.github.io/kuberay-helm
            helmChart: kuberay-operator
            helmVersion: 1.2.2
  template:
    metadata:
      name: 'kuberay-operator'
      namespace: argocd
      labels:
        app: kuberay-operator
        environment: '{{ .env }}'
    spec:
      project: '{{ .project }}'
      sources:
        - repoURL: '{{ .helmRepo }}'
          chart: '{{ .helmChart }}'
          targetRevision: '{{ .helmVersion }}'
          helm:
            releaseName: kuberay-operator
            valueFiles:
              - $values/ansible/argocd/config/kuberay-operator/values.yaml
        - repoURL: https://github.com/munhq/kubernetes_gpu.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
