apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kueue-setup
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: gpu
            namespace: gpu-workloads
            project: gpu
  template:
    metadata:
      name: 'kueue-setup'
      namespace: argocd
      labels:
        app: kueue-setup
        environment: '{{ .env }}'
    spec:
      project: '{{ .project }}'
      source:
        repoURL: https://github.com/munhq/kubernetes_gpu.git
        targetRevision: main
        path: ansible/argocd/charts/kueue-setup
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
