apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kueue
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: gpu
            namespace: gpu-workloads
            project: gpu
            helmRepo: oci://registry.k8s.io/kueue/charts
            helmChart: kueue
            helmVersion: 0.15.2
  template:
    metadata:
      name: 'kueue'
      namespace: argocd
      labels:
        app: kueue
        environment: '{{ .env }}'
    spec:
      project: '{{ .project }}'
      sources:
        - repoURL: https://github.com/kubernetes-sigs/kueue/releases/download/v0.10.1/kueue-0.10.1.tgz
          targetRevision: HEAD
          helm:
            releaseName: kueue
            valueFiles:
              - $values/ansible/argocd/config/kueue/values.yaml
        - repoURL: https://github.com/munhq/kubernetes_gpu.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
