replicaCount: 1

image:
  repository: ghcr.io/munhq/batch-inference-api
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret

service:
  type: NodePort
  port: 8000
  nodePort: 30800

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

serviceAccount:
  create: true
  name: gpu-api

rbac:
  create: true
  # Permissions needed to create/read/delete RayJobs
  rules:
    - apiGroups: ["ray.io"]
      resources: ["rayjobs"]
      verbs: ["create", "get", "list", "watch", "delete"]

env:
  - name: PORT
    value: "8000"
